Add prior art section art including peergos
decentralized-identity/secure-data-store pull request #101
Opened 2020-08-28 09:45 UTC by ianopolous

Fixes https://github.com/decentralized-identity/secure-data-store/issues/56

I wasn't sure exactly where to put the section, so I chose what seemed an appropriate place, but very happy to move it around.

2020-09-07 14:14 UTC, OR13 commented on index.html
> +              all data is in a merkle-champ (compressed hash-array mapped prefix-trie) which is a great data structure for content addressed mutable data, and plays very well with CRDTs as well.
Can you open a separate issue and provide an example of this data structure in JSON?

2020-09-07 14:15 UTC, OR13 commented on index.html
> +              access control is done with a version of <a href="https://github.com/Peergos/Peergos/raw/master/papers/wuala-cryptree.pdf">cryptree</a>, improved to fit in the ipfs data model, which is
Can you summarize this approach on a WG call?...preferably one of the next ones regarding authorization?

2020-09-07 14:18 UTC, ianopolous commented on index.html
> +              access control is done with a version of <a href="https://github.com/Peergos/Peergos/raw/master/papers/wuala-cryptree.pdf">cryptree</a>, improved to fit in the ipfs data model, which is
Sure. There's also more detail [here](https://book.peergos.org/security/cryptree.html)

2020-09-07 14:18 UTC, OR13 requested changes

2020-09-07 14:18 UTC, OR13 commented on index.html
> +          <a href="https://github.com/peergos/peergos">Peergos</a> has mostly the same requirements as SDS (actually stronger privacy and security requirements in several cases) and is built on top o
When encryption keys are compromised, doesn't all the cipher-text that was replicated over IPFS become plaintext?... seems like a weaker security property to me.... I'd rather not have CT be replicated without consent of the data controller, suggest elaborating on this IPFS issue more or removing this line.

2020-09-07 14:19 UTC, OR13 commented
@ianopolous sorry it took so long for you to get a review on this.... great work!

2020-09-07 14:39 UTC, ianopolous commented on index.html
> +          <a href="https://github.com/peergos/peergos">Peergos</a> has mostly the same requirements as SDS (actually stronger privacy and security requirements in several cases) and is built on top o
It is stronger security when the threat model includes a quantum computer, for example. Unshared files are already post-quantum in Peergos. Shared files have a time-limited window of vulnerability to a quantum computer, but even that will go away once we switch to PQ key exchange (hopefully CSIDH). In the case of key compromise the keys can be easily rotated for specific files or subtrees. That is how access is revoked for example. The server doesn't have a concept of access control. 

The privacy requirements are stronger around metadata protection (in data structures at rest for example). We go to great lengths to hide the size of individual files, even whether or not something is a file or a directory, and many more properties. And also treating the server (and underlying data store) as untrusted. We explicitly don't expose the social graph (who has been granted access to what) to the server. 

If you also worry about network level access to cipher text, then you can just run a private IPFS network in the short term, until network level access control is implemented. (We plan to do this eventually, but it requires us reimplementing the bits of IPFS we use first (mainly libp2p).) Note that depending on your threat model this might not matter. If your threat model includes a global passive adversary logging all traffic, then even network level access control won't help you.

2020-09-07 14:41 UTC, ianopolous commented on index.html
> +              all data is in a merkle-champ (compressed hash-array mapped prefix-trie) which is a great data structure for content addressed mutable data, and plays very well with CRDTs as well.
Sure. I could also add a reference to the original CHAMP paper, and explain why it is such a good structure for this situation? https://michael.steindorfer.name/publications/oopsla15.pdf

2020-09-07 16:33 UTC, OR13 commented on index.html
> +          <a href="https://github.com/peergos/peergos">Peergos</a> has mostly the same requirements as SDS (actually stronger privacy and security requirements in several cases) and is built on top o
#### Stronger because of PQ threat model.

This is a function of key agreement / symmetric keys chosen correct? If so this is no better than EDV from an architecture perspective.

#### Stronger because of directory structure metadata

This I agree with, but its not exactly fair to compare an encrypted access controlled FS to an access controlled structured data store.... I think there is a lot of value to be had by unpacking this further... or in considering peergos as a solution for EDV raw byte storage.

#### Regarding network activity

If the IPFS network is private, replication of ciphertexts is at the discretion of the network operator...  an attacker with read access to the private network, and private key compromise recovers plaintext... this is the same security scenario that EDVs currently have.

If the IPFS network is public, the attacker has read access to ciphertext and need only obtain private key compromise to recover plaintext. This is weaker security model than the EDV default (ciphertext is not access controlled by default / IPFS is a public network)

Are these assertions correct? If not please correct me.

I would still like to see the `(actually stronger privacy and security requirements in several cases)` removed, and replaced with a summary of the dialog we are having here.

2020-09-07 20:36 UTC, ianopolous commented on index.html
> +          <a href="https://github.com/peergos/peergos">Peergos</a> has mostly the same requirements as SDS (actually stronger privacy and security requirements in several cases) and is built on top o
PQ:
To get from nothing to logging in and viewing your files involves only hashing (scrypt, sha256) and symmetric encryption. Neither of which are significantly weakened by a quantum computer (only a 2X speedup via Grover's algorithm). Furthermore, when a user shares a file, the asymmetrically encrypted capability is *not* stored in ipfs, and deleted after it has been retrieved, and thus not vulnerable to a future quantum computer, only a currently existing one (or a global passive adversary able to log all traffic, and then get a quantum computer in the future). How exactly does an EDV handle access control or logging in?

> This I agree with, but its not exactly fair to compare an encrypted access controlled FS to an access controlled structured data store.... I think there is a lot of value to be had by unpacking this further... or in considering peergos as a solution for EDV raw byte storage.

To be clear I'm not proposing Peergos as a structured data store, at least no more structured than a filesystem. 

> If the IPFS network is private, replication of ciphertexts is at the discretion of the network operator... an attacker with read access to the private network, and private key compromise recovers plaintext... this is the same security scenario that EDVs currently have.

I'm not sure what threat model you're trying to present here. A private network for IPFS is simply a shared secret key chosen by the operator of the instance. If you don't want to "federate" with other instances then you can indeed just turn off ipfs. 

> If the IPFS network is public, the attacker has read access to ciphertext and need only obtain private key compromise to recover plaintext. This is weaker security model than the EDV default (ciphertext is not access controlled by default / IPFS is a public network)

How does an EDV implement access control here? Is that access control vulnerable to a quantum computer? Could a malicious EDV grant an unauthorised user access to plaintext? (That's not possible in Peergos - we explicitly don't trust the server in our threat model)

> I would still like to see the (actually stronger privacy and security requirements in several cases) removed, and replaced with a summary of the dialog we are having here.

Sure, I can do that.

2020-09-08 01:08 UTC, OR13 commented on index.html
> +          <a href="https://github.com/peergos/peergos">Peergos</a> has mostly the same requirements as SDS (actually stronger privacy and security requirements in several cases) and is built on top o
> PQ:
> To get from nothing to logging in and viewing your files involves only hashing (scrypt, sha256) and symmetric encryption. Neither of which are significantly weakened by a quantum computer (only a 2X speedup via Grover's algorithm). Furthermore, when a user shares a file, the asymmetrically encrypted capability is _not_ stored in ipfs, and deleted after it has been retrieved, and thus not vulnerable to a future quantum computer, only a currently existing one (or a global passive adversary able to log all traffic, and then get a quantum computer in the future). How exactly does an EDV handle access control or logging in?
> 

It's the subject of the last wg call, and the next one. The current implementations rely on EdDSA / Ed25519... so EC discrete log problem... https://bitcoin.stackexchange.com/questions/57965/are-schnorr-signatures-quantum-computer-resistant

So assuming EdDSA is broken, the attacker gains the ciphertext.

> > This I agree with, but its not exactly fair to compare an encrypted access controlled FS to an access controlled structured data store.... I think there is a lot of value to be had by unpacking this further... or in considering peergos as a solution for EDV raw byte storage.
> 
> To be clear I'm not proposing Peergos as a structured data store, at least no more structured than a filesystem.
> 

I'd love to hear more about the approach you took, and how you see filesystems and access controlled web servers interacting in decentralized web applications.

> > If the IPFS network is private, replication of ciphertexts is at the discretion of the network operator... an attacker with read access to the private network, and private key compromise recovers plaintext... this is the same security scenario that EDVs currently have.
> 
> I'm not sure what threat model you're trying to present here. A private network for IPFS is simply a shared secret key chosen by the operator of the instance. If you don't want to "federate" with other instances then you can indeed just turn off ipfs.
> 

The question is: what material is federated with other instances when IPFS is open / compromised. I am assuming its ciphertexts encrypted with symmetric keys.... thats quantum resistant, but the keys have a shelf life, and if you assume that the symmetric keys are eventually blown, an open network of ciphertexts is indistinguishable from an open network of plaintexts... on a long enough timeline.

> > If the IPFS network is public, the attacker has read access to ciphertext and need only obtain private key compromise to recover plaintext. This is weaker security model than the EDV default (ciphertext is not access controlled by default / IPFS is a public network)
> 
> How does an EDV implement access control here? Is that access control vulnerable to a quantum computer? Could a malicious EDV grant an unauthorised user access to plaintext? (That's not possible in Peergos - we explicitly don't trust the server in our threat model)
> 

Worst case for an EDV today, the server can hand out ciphertexts, that are encrypted with `ECDH-ES+A256KW`.

Whats the worst thing a Peergos server can do, with or without a public IPFS network?

> > I would still like to see the (actually stronger privacy and security requirements in several cases) removed, and replaced with a summary of the dialog we are having here.
> 
> Sure, I can do that.

Thanks!

2020-09-08 08:06 UTC, ianopolous commented on index.html
> +          <a href="https://github.com/peergos/peergos">Peergos</a> has mostly the same requirements as SDS (actually stronger privacy and security requirements in several cases) and is built on top o
> I'd love to hear more about the approach you took, and how you see filesystems and access controlled web servers interacting in decentralized web applications.

The approach we take is similar to the unix philosophy where everything is a file. We posit that an access controlled file system is sufficient to build pretty much any application. 

> The question is: what material is federated with other instances when IPFS is open / compromised. I am assuming its ciphertexts encrypted with symmetric keys.... thats quantum resistant, but the keys have a shelf life, and if you assume that the symmetric keys are eventually blown, an open network of ciphertexts is indistinguishable from an open network of plaintexts... on a long enough timeline.

With that threat model even TLS isn't safe. The property that is normally desired here is Forward Secrecy. TLS and protocols like Signal obtain that by throwing away old keys and constantly rotating to new keys. To achieve that in Peergos is similar, you just need to rotate the keys for a file (every file has different encryption keys).

> Worst case for an EDV today, the server can hand out ciphertexts, that are encrypted with ECDH-ES+A256KW.

This is the crux of the matter - something encrypted with ECDH-ES+A256KW is broken and plaintext readable by a quantum computer. This is where Peergos is stronger. We don't rely on asymmetric encryption *anywhere* for privacy of files that aren't shared. The worst thing that a Peergos server could do would be to withhold valid updates or delete data, and even those are trivially mitigated and detected by running a mirror.

2020-09-17 20:00 UTC, OR13 commented on index.html
> +              all data is in a merkle-champ (compressed hash-array mapped prefix-trie) which is a great data structure for content addressed mutable data, and plays very well with CRDTs as well.
yes, please add the reference.

2020-09-17 20:00 UTC, OR13 commented on index.html
> +          <a href="https://github.com/peergos/peergos">Peergos</a> has mostly the same requirements as SDS (actually stronger privacy and security requirements in several cases) and is built on top o
can you add something to this effect to the PR?

2020-09-18 13:09 UTC, OR13 approved these changes

2020-09-20 18:39 UTC, OR13 commented
@msporny @csuwildcat editors to review.

2020-09-20 18:54 UTC, msporny requested changes
Reads like an advertisement for Peergos rather than how it applies to the specification. These sorts of sections tend to go in a Use Cases, Requirements, and Prior Art document, not a core specification.

I don't object to this being merged in, but expect that it'll get removed in time and moved to Use Cases or another NOTE.

Can we move this over to the use cases document?

2020-09-21 15:44 UTC, OR13 commented
I agree use cases may be better, however, its currently a markdown document.... I suggest we convert it to respec and then merge this there.

2020-09-29 02:17 UTC, OR13 commented
@msporny I suggest we take this PR, and then editors merge in into a use cases document.

2020-10-19 20:16 UTC, merged