First stab at Hub section in spec
decentralized-identity/secure-data-store pull request #118
Opened 2020-10-19 16:17 UTC by csuwildcat

This is to be regarded as a strawman PR to open the discussion about what makes up a Hub and what things we may need to define within the scope of the spec.

2020-10-19 16:38 UTC, OR13 requested changes
I think there are 2 sections which are missing from this, which we need to manage alignment.

1. Data Model
1.1 Profiles
1.2 Collections
1.3 Commitments
2. Interfaces 
2.1 CRUD (HTTP + POST)

please add these 2 top level sections under Identity Hubs, and move the examples to these sections, and reference them by link from the associated other sections... 

These 2 sections are where we will need to get crystal clear, and it will be hard chasing examples down if we don't formalize things like this.

2020-10-19 16:38 UTC, OR13 commented on index.html
> +    <h2>Identity Hubs</h2>
may want to add an issue linking to the naming debate issue... for example:

```
<p class="issue" data-number="423">
The Working Group is still debating naming of this instance and its associated interfaces and data model.
</p>
```

2020-10-19 16:38 UTC, OR13 commented on index.html
> +  "@context": "https://identity.foundation/schemas/hub/v0.1",
please open an issue to make this a resolvable URL... https://identity.foundation/schemas/hub/v0.1

2020-10-19 16:38 UTC, OR13 commented on index.html
> +          an object in the system. To derive the ID of an object, generate a Base64URL-encoded SHA-256 multihash
We need to have a come to jesus moment regarding base58 vs base64url.... can you open an issue regarding this?

2020-10-19 16:38 UTC, OR13 commented on index.html
> +      <h3>Object State Syncronization</h3>
glad that we have split replication and synchronization.

2020-10-19 16:38 UTC, OR13 commented on index.html
> +    "strategy": "crdt-delta",
this should have its own section under synchronization.

2020-10-19 16:45 UTC, csuwildcat commented on index.html
> +          an object in the system. To derive the ID of an object, generate a Base64URL-encoded SHA-256 multihash
Issue here: https://github.com/decentralized-identity/secure-data-store/issues/119

2020-10-19 18:01 UTC, csuwildcat commented on index.html
> +    "strategy": "crdt-delta",
I had subsections for different sync strategies, are you talking about something in addition or different?

2020-10-19 18:13 UTC, OR13 commented on index.html
> +    "strategy": "crdt-delta",
then we are good,

2020-10-19 20:32 UTC, OR13 approved these changes
I'd like to merge this, and then do another round of editorial cleanup. we need to get the spec ready to take PRs from the group.

2020-10-27 01:02 UTC, dmitrizagidulin approved these changes
👍

2020-10-27 01:32 UTC, OR13 commented
@csuwildcat to move appendix A into hubs, and fix the sidebar navigation.

2020-10-27 12:17 UTC, llorllale commented on index.html
> +      and values that best describe them. The Profile interface is addressed via the following methods:
copy pasta from above - this paragraph should be about collections

2020-10-27 12:18 UTC, llorllale approved these changes

2020-10-31 20:31 UTC, OR13 commented
Merging, will need lots of editorial cleanup.

2020-10-31 20:31 UTC, merged